### ISSUE TITLE
StateStyles crash

### ISSUE THREAD

**Issue by jlrussin** [goki/gi#74] opened 2018-08-26 16:05 UTC
I have no idea what this is supposed to do but I found it crashed whenever I clicked StateStyles in any of the widgets. For example:

./widgets
Received button signal: ButtonPressed from button: button2
Received button signal: ButtonReleased from button: button2
Received button signal: ButtonClicked from button: button2
GiEditor: Tree changed with signal: NodeSignalUpdated
2018/08/26 09:55:56 TableView requires that you pass a pointer to a slice of struct elements -- ptr doesn't point to a slice: [6]gi.Style
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x43ab9bd]

goroutine 7 [running]:
github.com/goki/gi/giv.(*TableView).TableViewEvents(0xc00ac2e600)
	/Users/Jake/go/src/github.com/goki/gi/giv/tableview.go:1716 +0xfd
github.com/goki/gi/giv.(*TableView).Render2D(0xc00ac2e600)
	/Users/Jake/go/src/github.com/goki/gi/giv/tableview.go:828 +0x73
github.com/goki/gi.(*Layout).Render2DChildren(0xc00bc18a00)
	/Users/Jake/go/src/github.com/goki/gi/layout.go:1208 +0xab
github.com/goki/gi.(*Frame).Render2D(0xc00bc18a00)
	/Users/Jake/go/src/github.com/goki/gi/frame.go:149 +0x8f
github.com/goki/gi.(*Node2DBase).Render2DChildren(0xc00bc14000)
	/Users/Jake/go/src/github.com/goki/gi/node2d.go:599 +0xa2
github.com/goki/gi.(*Viewport2D).Render2D(0xc00bc14000)
	/Users/Jake/go/src/github.com/goki/gi/viewport2d.go:410 +0x6d
github.com/goki/gi.(*Node2DBase).Render2DTree(0xc00bc14000)
	/Users/Jake/go/src/github.com/goki/gi/node2d.go:560 +0x82
github.com/goki/gi.(*Node2DBase).FullRender2DTree(0xc00bc14000)
	/Users/Jake/go/src/github.com/goki/gi/node2d.go:472 +0x89
github.com/goki/gi.(*Window).FullReRender(0xc00bc2e000)
	/Users/Jake/go/src/github.com/goki/gi/window.go:501 +0x4f
github.com/goki/gi.(*Window).EventLoop(0xc00bc2e000)
	/Users/Jake/go/src/github.com/goki/gi/window.go:926 +0x65f
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/Jake/go/src/github.com/goki/gi/window.go:440 +0x3f

**Comment by rohrlich** [comment] 2018-08-26 16:07
I believe this is a duplicate of #54

**Comment by rcoreilly** [comment] 2018-08-27 07:54
You mean #59 -- yep, dupe of that.  anyway crash fixed.

**Closed by rcoreilly** 2018-08-27 07:54 UTC
