### ISSUE TITLE
text-align not behaving as expected

### ISSUE THREAD

**Issue by buck54321** [goki/gi#419] opened 2020-11-27 20:38 UTC
On Linux Mint

```go
package main

import (
	"github.com/goki/gi/gi"
	"github.com/goki/gi/gimain"
	"github.com/goki/ki/ki"
)

func main() {
	gimain.Main(func() {
		mainWin := gi.NewMainWindow("my-window", "My App", 1024, 768)

		vp := mainWin.WinViewport2D()
		updt := vp.UpdateStart()

		mainFrame := mainWin.SetMainFrame()
		mainFrame.SetStretchMaxWidth()

		lbl := gi.AddNewLabel(mainFrame, "lbl", "dummy text")
		lbl.SetProps(ki.Props{
			"text-align":   "center",
			"border-width": 1,
			"width":        500,
		}, false)

		mainWin.SetCloseCleanFunc(func(w *gi.Window) {
			go gi.Quit()
		})

		vp.UpdateEndNoSig(updt)
		mainWin.StartEventLoop()
	})
}
```

Expected the text to be centered within the width of the label, but instead it is right-aligned. Setting `text-align: right` moves the text outside of the label altogether. 

![image](https://user-images.githubusercontent.com/6109680/100482727-c7903100-30bd-11eb-8341-99003cf3d864.png)

**Comment by rcoreilly** [comment] 2020-11-28 09:56
This had me puzzled for a bit, but I think I've figured out what the issue is.  Basically, the Label layout code is not properly handling the case of a specified "width" property, in relation to its own computed positioning and width.  If you set the label max-width to -1 (stretch) then it centers it fully, and the box takes up the whole area, but specifying a fixed width produces some improper amalgam of its own computed alignment-based layout and width, and the specified width.  This Label layout code handles iterative resizing to fit constraints, so it is a bit complex, and that case was not properly tested.  Will look at it later when I get a chance -- I've updated the basic.go example to demonstrate the issue.

Also, technically you should need to specify "align": "center" too but that doesn't seem to make a diff.. not sure if it falls back on text-align or what.

**Comment by buck54321** [comment] 2020-11-29 10:43
Probably related, but I'm having trouble achieving a particular effect. I need a fixed width horizontal `Layout` with two labels. The left label's text should be left aligned. The right label's text should be right-aligned, and the right label itself should be aligned to the right side of the parent. Something like

![image](https://user-images.githubusercontent.com/6109680/100539610-4f308980-31fd-11eb-95a4-ade0f9236582.png)

From the docs, my initial thoughts were to try

```
row := gi.AddNewFrame(mainFrame, "row", gi.LayoutHoriz)
row.SetProps(ki.Props{"width": 750, "horizontal-align": "center"}, false)
gi.AddNewLabel(row, "leftBox", "this text should be left-aligned")
gi.AddNewStretch(row, "stretch")
rightBox := gi.AddNewLabel(row, "rightBox", "this should be right-aligned")
rightBox.SetProps(ki.Props{"text-align": "right"}, false)
```
Which gives me

![image](https://user-images.githubusercontent.com/6109680/100539327-50f94d80-31fb-11eb-9602-2eeb0794ed77.png)

I then thought to insert additional sized vertical layouts and set the `horizontal-align` property of the labels. So I tried this, with varying flavors of CSS.

```go
row := gi.AddNewFrame(mainFrame, "row", gi.LayoutHoriz)
row.SetProps(ki.Props{"width": 800, "horizontal-align": "center", "overflow": "visible", "margin": 0, "padding": 0}, false)
leftLyt := gi.AddNewFrame(row, "leftLyt", gi.LayoutVert)
leftLyt.SetProps(ki.Props{"width": 400, "margin": 0, "padding": 0}, false)
leftLbl := gi.AddNewLabel(leftLyt, "leftLbl", "this text should be left-aligned")
leftLbl.SetProps(ki.Props{"horizontal-align": "left", "margin": 0, "padding": 0}, false)
rightLyt := gi.AddNewFrame(row, "rightLyt", gi.LayoutVert)
rightLyt.SetProp("width", 400)
rightLbl := gi.AddNewLabel(rightLyt, "rightLbl", "this should be right-aligned")
rightLbl.SetProps(ki.Props{"horizontal-align": "right", "margin": 0, "padding": 0}, false)
```

Which gave me 

![image](https://user-images.githubusercontent.com/6109680/100539538-da5d4f80-31fc-11eb-8e3b-9372b9d8f7de.png)

Which might be close. I can't tell, Shouldn't `overflow: visible;` remove scroll bars?

**Comment by rcoreilly** [comment] 2020-11-29 13:19
try the first version without right alignment?  The stretch will achieve the right align anyway.  There are clearly conflicts between the text-level alignment and the layout-level arrangement of items -- I'll see if there are ways of making that work more sensibly.

**Comment by rcoreilly** [comment] 2020-11-30 01:50
yeah it was pretty broken!  was not updated once text alignment happened separately in text layout mechanism, and the widget-level and text-level alignment settings were linked which is not good..  see the new align example for new correct behavior, and hopefully your cases now work -- please update this if not. 

I still need to do more testing and look for existing text-align settings etc and also add vertical test cases to align.

**Comment by rcoreilly** [comment] 2020-11-30 13:31
if latest is working for you now, you can close this issue, or update with further details on what isn't working.  It looks good to me in my tests.

**Closed** 2020-12-23 01:05 UTC
