### ISSUE TITLE
completion issues

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#166] opened 2018-10-26 22:07 UTC
now that completion is usable :)  looks like are some issues:

* in giv/fileview.go:628 -- completion on ef (*gi.TextField) shows .Text as a variable, but it is a function.

* strings. does not complete with all the strings methods -- that is one of the most important use-cases -- remembering all those package methods!  but then it DID complete with .Split when i was typing: strings.Split(exts.  

* typing: ef : gives a large list of options.. (only valid completion should be := right?)

seems like maybe it is not quite getting the right seed or something?

**Comment by rohrlich** [comment] 2018-10-26 22:21
Good, I'll start looking at these.

**Comment by rohrlich** [comment] 2018-10-26 22:53
• in giv/fileview.go:628 -- completion on ef (*gi.TextField) shows .Text as a variable, but it is a function.
-- I don't see ef but if I do completion on a gi.TextField .Text shows as a function. The type is returned by gocode. If it is a problem I will file it.

• strings. does not complete with all the strings methods -- that is one of the most important use-cases -- remembering all those package methods! but then it DID complete with .Split when i was typing: strings.Split(exts.
-- the problem I see is that for Builder, Reader, Replacer they type is listed as a completion but not the funcs. Is that what you are referring to?

• typing: ef : gives a large list of options.. (only valid completion should be := right?)
-- right you are! Yep, likely the wrong seed, I'll take a look.

**Comment by rohrlich** [comment] 2018-10-26 23:03
• ef ...
-- I had forgotten but for the gocode version of completion I handoff the entire file as a slice of bytes so the problem is there.

**Comment by rohrlich** [comment] 2018-10-26 23:13
Meant to add this along with my response to the line 628 issue
![screen shot 2018-10-26 at 4 42 04 pm](https://user-images.githubusercontent.com/22350787/47596261-498f5800-d942-11e8-892e-bd0611bc3b94.png)

**Comment by rohrlich** [comment] 2018-10-27 00:43
I thought about this again. I always produce a seed from the current edit and in this case the seed is "". When the seed is empty I show all of the results, hence the long incorrect list. Perhaps it would be better to show none when the seed is empty unless the user has specifically invoked completion (control + .). So the default behavior would be to wait for at least one char beyond whitespace.

**Comment by rcoreilly** [comment] 2018-10-27 00:48
FWIW I just added logic that does not do completion on space..  overall the timing logic etc is looking better and hopefully won't crash (I was getting crashes from the separate routine).  I'll followup with more updates as I use it more.

**Comment by rohrlich** [comment] 2018-10-27 00:58
I'm finding you can get into a state where you don't get completion even if you specifically invoke.

**Comment by rcoreilly** [comment] 2018-10-27 00:59
yeah, definitely want to not complete on empty seed.  key case is backspace: if you backspace all the way in widgets, you get the full list of words, which is not useful.. we can leave that logic up to the completion function user so they can do it if they want, but generally probably don't want to.

and let me know if you can reproduce not getting completion.

**Comment by rohrlich** [comment] 2018-10-27 01:02
I updated my repository but didn't rebuild so I'll give it another try

**Comment by rohrlich** [comment] 2018-10-27 02:57
We now have the situation pictured when you backspace and only have whitespace remaining. ShowCompletions is never called because we return and thus the pop timer code is called so the popup isn't removed. Previously the popup was closed before we even checked whether we would complete or not as it is always recreated. Not sure if you are still tinkering with that code or I should fix.

**Comment by rcoreilly** [comment] 2018-10-27 03:05
Not working on it - go ahead and fix.

**Comment by rohrlich** [comment] 2018-10-29 23:18
Popup disappears when you start moving down the list of completions.

Popup completer and control+n or arrow key and after first step the completer disappears. I think it is since the timer was added.

**Comment by rohrlich** [comment] 2018-10-30 18:47
Completion of go code working much better. I commented out that code that I wrote to preprocess before calling gocode and now completion is generally much better. It still makes the mistakes I was trying to prevent but there is certainly a bug in my code so better to leave it commented out for now.

Closing and moving the bug mentioned in previous comment to separate issue

**Closed by rohrlich** 2018-10-30 18:47 UTC
