### ISSUE TITLE
Problems with external monitor recurring

### ISSUE THREAD

**Issue by StephenJRead** [goki/gi#305] opened 2019-12-01 20:26 UTC
I had the bg project open on my external LG monitor (Mac laptop) and initially it behaved itself.  But it has been open for at least the last day or so and I just noticed that the main window had expanded to many times its normal size and it had turned completely black.  It used to do this immediately upon opening, but now it takes a day or so.

**Comment by rcoreilly** [comment] 2019-12-01 20:51
There are definitely some remaining issues with wake / sleep cycles -- unfortunately I'm not able to reproduce them locally at a short time scale -- somehow they only appear for me overnight, which makes it very difficult to debug!  can you test putting your computer & display to sleep and waking it up?

**Comment by StephenJRead** [comment] 2019-12-01 21:26
I can, but if I can replicate the problem, what data do you want me to send?  I might get messages in the Terminal window and I can send those.  Anything else?


On Dec 1, 2019, at 12:51 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


There are definitely some remaining issues with wake / sleep cycles -- unfortunately I'm not able to reproduce them locally at a short time scale -- somehow they only appear for me overnight, which makes it very difficult to debug! can you test putting your computer & display to sleep and waking it up?

**Comment by StephenJRead** [comment] 2019-12-01 21:27
My guess is that it is more likely to happen when the main window is on the external monitor.


On Dec 1, 2019, at 12:51 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


There are definitely some remaining issues with wake / sleep cycles -- unfortunately I'm not able to reproduce them locally at a short time scale -- somehow they only appear for me overnight, which makes it very difficult to debug! can you test putting your computer & display to sleep and waking it up?

**Comment by rcoreilly** [comment] 2019-12-01 21:28
in my experience there are no messages. if you can reliably reproduce we can add some useful debug code.

**Comment by StephenJRead** [comment] 2019-12-01 21:29
okay.


On Dec 1, 2019, at 1:28 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


in my experience there are no messages. if you can reliably reproduce we can add some useful debug code.

**Comment by StephenJRead** [comment] 2019-12-01 21:36
Well, I have put it to sleep multiple times on both the internal and external monitors and so far, nothing weird.  I also used the green button to go back and forth between full screen and that didn’t make a difference either.
   I will let you know if I can figure out how to reliably trigger it.


On Dec 1, 2019, at 1:28 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


in my experience there are no messages. if you can reliably reproduce we can add some useful debug code.

**Comment by StephenJRead** [comment] 2019-12-01 23:03
So I walked away from my computer for about 45 minutes and when I came back the screen had expanded and was all black (on the external monitor).  Here is what is in the terminal window, for what it is worth.  Notice that this terminal window had been opened just to run this instance of bg, so there was something over 2 hours before I got this error.


Last login: Sun Dec  1 12:19:53 on ttys001
/Applications/Emergent\ Go/mac/mac\ binaries/ch7/bg ; exit;
(base) StephenReadsMBP:~ read$ /Applications/Emergent\ Go/mac/mac\ binaries/ch7/bg ; exit;
OpenGL version 4.1 INTEL-12.10.12
2019/12/01 14:55:29 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
501 = INVALID_VALUE: Given when a value parameter is not a legal value for that function. This is only given for local problems; if the spec allows the value in certain circumstances, where other parameters or state dictate those circumstances, then GL_INVALID_OPERATION is the result instead.
2019/12/01 14:55:29 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
glgpu gpu.Framebuffer:  not complete -- this usually means you need to set your GoGi prefs to Smooth3D = off, and restart
2019/12/01 14:55:29 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
501 = INVALID_VALUE: Given when a value parameter is not a legal value for that function. This is only given for local problems; if the spec allows the value in certain circumstances, where other parameters or state dictate those circumstances, then GL_INVALID_OPERATION is the result instead.
2019/12/01 14:55:29 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:55:31 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
glgpu gpu.Framebuffer:  not complete -- this usually means you need to set your GoGi prefs to Smooth3D = off, and restart
2019/12/01 14:55:31 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:34 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
501 = INVALID_VALUE: Given when a value parameter is not a legal value for that function. This is only given for local problems; if the spec allows the value in certain circumstances, where other parameters or state dictate those circumstances, then GL_INVALID_OPERATION is the result instead.
2019/12/01 14:58:34 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
glgpu gpu.Framebuffer:  not complete -- this usually means you need to set your GoGi prefs to Smooth3D = off, and restart
2019/12/01 14:58:34 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
501 = INVALID_VALUE: Given when a value parameter is not a legal value for that function. This is only given for local problems; if the spec allows the value in certain circumstances, where other parameters or state dictate those circumstances, then GL_INVALID_OPERATION is the result instead.
2019/12/01 14:58:34 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:35 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
glgpu gpu.Framebuffer:  not complete -- this usually means you need to set your GoGi prefs to Smooth3D = off, and restart
2019/12/01 14:58:36 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:37 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
501 = INVALID_VALUE: Given when a value parameter is not a legal value for that function. This is only given for local problems; if the spec allows the value in certain circumstances, where other parameters or state dictate those circumstances, then GL_INVALID_OPERATION is the result instead.
2019/12/01 14:58:37 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
glgpu gpu.Framebuffer:  not complete -- this usually means you need to set your GoGi prefs to Smooth3D = off, and restart
2019/12/01 14:58:37 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
501 = INVALID_VALUE: Given when a value parameter is not a legal value for that function. This is only given for local problems; if the spec allows the value in certain circumstances, where other parameters or state dictate those circumstances, then GL_INVALID_OPERATION is the result instead.
2019/12/01 14:58:37 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
glgpu gpu.Framebuffer: scene-frame not complete -- this usually means you need to set your GoGi prefs to Smooth3D = off, and restart
glgpu gpu.Framebuffer: scene-frame not complete -- this usually means you need to set your GoGi prefs to Smooth3D = off, and restart
2019/12/01 14:58:41 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
501 = INVALID_VALUE: Given when a value parameter is not a legal value for that function. This is only given for local problems; if the spec allows the value in certain circumstances, where other parameters or state dictate those circumstances, then GL_INVALID_OPERATION is the result instead.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
glgpu gpu.Framebuffer: scene-frame not complete -- this usually means you need to set your GoGi prefs to Smooth3D = off, and restart
2019/12/01 14:58:41 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: obj render:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
glgpu gpu.Framebuffer:  not complete -- this usually means you need to set your GoGi prefs to Smooth3D = off, and restart
2019/12/01 14:58:41 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:58:41 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/12/01 14:59:23 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2019/12/01 14:59:23 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2019/12/01 14:59:24 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2019/12/01 14:59:24 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2019/12/01 14:59:29 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2019/12/01 14:59:29 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.


On Dec 1, 2019, at 1:28 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


in my experience there are no messages. if you can reliably reproduce we can add some useful debug code.

**Comment by rcoreilly** [comment] 2019-12-02 03:36
Hmm.  I don't get that error -- but I mainly leave the gide editor open and it doesn't do the 3D stuff that seems to be causing the problem here. I'll try leaving an emer sim open and see if I can get some useful info.

**Comment by rcoreilly** [comment] 2020-03-23 10:14
we have a few of these same issues tracking under emergent -- I'm closing this one and please follow up on the emergent-specific issue.

**Closed by rcoreilly** 2020-03-23 10:14 UTC
