### ISSUE TITLE
dropfile

### ISSUE THREAD

**Issue by ddkwork** [goki/gi#683] opened 2023-12-25 15:30 UTC
how to use this api？

![Screenshot_20231225_232952_com.realvnc.viewer.android.jpg](https://github.com/goki/gi/assets/19886504/677d6b57-64a9-4b78-b61d-3df33f0708c1)

**Comment by kkoreilly** [comment] 2023-12-25 17:22
This is a duplicate of #33, which we are planning to implement soon by the v2 release.

**Closed by kkoreilly** 2023-12-25 17:22 UTC
