### ISSUE TITLE
global filter

### ISSUE THREAD

**Issue by ddkwork** [goki/gi#734] opened 2023-12-31 04:15 UTC
Implement global fuzzy search of trees, tables, and tree tables

![Screenshot_20231231_121411_com.microsoft.emmx.jpg](https://github.com/goki/gi/assets/19886504/fc84a0b5-eaf1-438d-ab69-9dbc617eef77)

https://primevue.org/treetable

**Comment by kkoreilly** [comment] 2023-12-31 04:32
This is a duplicate of #28, which should be implemented soon.

**Closed by kkoreilly** 2023-12-31 04:32 UTC
